In [3]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
df=pd.read_csv("BSP.csv")
df.head()

,date,gender,age,address,famsize,Pstatus,M_Edu,F_Edu,M_Job,F_Job,relationship,smoker,tuition_fee,time_friends,ssc_result,hsc_result
0,29/04/2018,M,18,Rural,GT3,Together,3,2,At_home,Farmer,No,No,71672,4,4.22,3.72
1,29/04/2018,F,19,Rural,LE3,Apart,0,4,Other,Health,Yes,No,26085,5,3.47,2.62
2,29/04/2018,F,19,Rural,GT3,Together,0,3,Teacher,Services,No,No,40891,3,3.32,2.56
3,29/04/2018,F,19,Rural,LE3,Apart,2,3,At_home,Business,No,No,50600,2,4.57,4.17
4,29/04/2018,M,17,Rural,GT3,Together,1,1,At_home,Farmer,No,No,62458,2,4.50,3.94

In [4]:
! pip install ydata-profiling

Requirement already satisfied: ydata-profiling in d:\anaconda3\lib\site-packages (4.18.1)
Requirement already satisfied: scipy<1.17,>=1.8 in d:\anaconda3\lib\site-packages (from ydata-profiling) (1.15.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in d:\anaconda3\lib\site-packages (from ydata-profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in d:\anaconda3\lib\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in d:\anaconda3\lib\site-packages (from ydata-profiling) (2.10.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in d:\anaconda3\lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in d:\anaconda3\lib\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in d:\anaconda3\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in d:\anaconda3\lib\site-packages (from ydata-profiling) (2.1.3)
Requirement already satisfied: minify-html>=0.15.0 in d:\anaconda3\lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in d:\anaconda3\lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in d:\anaconda3\lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in d:\anaconda3\lib\site-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.66.3 in d:\anaconda3\lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in d:\anaconda3\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in d:\anaconda3\lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in d:\anaconda3\lib\site-packages (from ydata-profiling) (0.14.4)
Requirement already satisfied: typeguard<5,>=4 in d:\anaconda3\lib\site-packages (from ydata-profiling) (4.4.4)
Requirement already satisfied: imagehash==4.3.2 in d:\anaconda3\lib\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in d:\anaconda3\lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in d:\anaconda3\lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in d:\anaconda3\lib\site-packages (from ydata-profiling) (0.61.0)
Requirement already satisfied: PyWavelets in d:\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.8.0)
Requirement already satisfied: pillow in d:\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (10.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\anaconda3\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in d:\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.1)
Requirement already satisfied: cycler>=0.10 in d:\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in d:\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in d:\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in d:\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in d:\anaconda3\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in d:\anaconda3\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in d:\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in d:\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in d:\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2025.4.26)
Requirement already satisfied: patsy>=0.5.6 in d:\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: colorama in d:\anaconda3\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in d:\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (24.3.0)
Requirement already satisfied: networkx>=2.4 in d:\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.4.2)
Requirement already satisfied: puremagic in d:\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (1.30)
Requirement already satisfied: six>=1.5 in d:\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [5]:
%pip install ydata-profiling
from ydata_profiling import ProfileReport

Requirement already satisfied: ydata-profiling in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (4.18.1)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (1.16.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (2.2.0)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (3.8.2)
Requirement already satisfied: pydantic<3,>=2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (2.12.5)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions[type_image_path]<0.8.2,>=0.7.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (1.26.3)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (4.4.4)
Requirement already satisfied: imagehash==4.3.2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (10.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.47.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.8.2)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2023.4)
Requirement already satisfied: joblib>=0.14.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\user\appdata\roaming\python\python311\site-packages (from pydantic<3,>=2->ydata-profiling) (4.14.1)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.1.4)
Requirement already satisfied: patsy>=0.5.6 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python311\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Requirement already satisfied: puremagic in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (1.30)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: visions 0.8.1 does not provide the extra 'type_image_path'

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
from ydata_profiling import ProfileReport

In [7]:
profile=ProfileReport(df,title="BSP",explorative=True)
profile.to_file("ydata.html")

100%|██████████| 16/16 [00:00<00:00, 60.67it/s]1<00:00, 12.27it/s, Describe variable: hsc_result]
Summarize dataset: 100%|██████████| 34/34 [00:07<00:00,  4.75it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:12<00:00, 12.68s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.09s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 42.23it/s]

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import VotingRegressor ,StackingRegressor,RandomForestRegressor,GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score 
from sklearn.linear_model import LinearRegression,Ridge

In [9]:
df=pd.read_csv("BSP.csv")

df.drop(columns=["date"],inplace=True)
df.columns

Index(['gender', 'age', 'address', 'famsize', 'Pstatus', 'M_Edu', 'F_Edu',
       'M_Job', 'F_Job', 'relationship', 'smoker', 'tuition_fee',
       'time_friends', 'ssc_result', 'hsc_result'],
      dtype='object')

In [10]:
corr_target=df.select_dtypes(include=np.number).corr()['hsc_result'].sort_values(ascending=False)
corr_target

hsc_result      1.000000
ssc_result      0.950178
M_Edu           0.063776
F_Edu           0.054811
tuition_fee     0.038068
age            -0.009857
time_friends   -0.156356
Name: hsc_result, dtype: float64

In [11]:
X=df.drop('hsc_result',axis=1)

y=df['hsc_result']

In [12]:
##Pipeline 
##numerical
num_transformer=Pipeline(
    steps=[
        ('impute',SimpleImputer(strategy='median')),
        ('scaler',StandardScaler())


    ]

)

In [13]:
##categorical 
cat_transformer=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('encoder',OneHotEncoder(handle_unknown='ignore'))
        
    ]


)

In [14]:
##train test 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
#Ensemble Learning '
#base learner
reg_lr=LinearRegression()
reg_rf=RandomForestRegressor(n_estimators=100,random_state=42)  
reg_gb=GradientBoostingRegressor(n_estimators=100,random_state=42)

In [16]:
##Voting
voting_reg=VotingRegressor(
    estimators=[('lr',reg_lr),('rf',reg_rf),('gb',reg_gb)]


)

In [17]:
#Stacking 
stacking_reg=StackingRegressor(
    estimators=[('lr',reg_lr),('rf',reg_rf),('gb',reg_gb)],
    final_estimator=Ridge()##the meta learner 
)

In [18]:
model_to_train ={
    'LinearRegression':reg_lr,
    "RamdomForest":reg_rf,
    "GradientBoosting":reg_gb,
    'Voting Ensemble':voting_reg,
    "Stacking Ensemble":stacking_reg    


}

In [19]:
result=[]
for name,model in model_to_train.items():
    pipe=Pipeline(
        [
            ('preprocessor',ColumnTransformer(
                transformers=[
                    ('num',num_transformer,X.select_dtypes(include=np.number).columns),
                    ('cat',cat_transformer,X.select_dtypes(exclude=np.number).columns)
                ]
            )),
            ('model',model)
        ]
    )
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    r2=r2_score(y_test,y_pred)
    mae=mean_absolute_error(y_test,y_pred)  
    mse=mean_squared_error(y_test,y_pred)
    result.append(
        {
            'Model':name,
            'r2_score':r2,
            'mae':mae,  
            'mse':mse




        }
    )
result_df=pd.DataFrame(result).sort_values(by='r2_score',ascending=False)

In [20]:
result_df

               Model  r2_score       mae       mse
2   GradientBoosting  0.959565  0.098902  0.015155
4  Stacking Ensemble  0.959405  0.098687  0.015215
3    Voting Ensemble  0.957528  0.100838  0.015919
1       RamdomForest  0.950248  0.108201  0.018647
0   LinearRegression  0.945920  0.111376  0.020269

In [21]:
best_model_name=result_df.iloc[0]['Model']
best_model_object=model_to_train[best_model_name]

final_pipe=Pipeline(
    [
        ('preprocessor',ColumnTransformer(
            transformers=[
                ('num',num_transformer,X.select_dtypes(include=np.number).columns),
                ('cat',cat_transformer,X.select_dtypes(exclude=np.number).columns)
            ]
        )),
        ('model',best_model_object)
    ]
)
final_pipe.fit(X_train,y_train)
y_final_pred=final_pipe.predict(X_test)

In [22]:
import seaborn as sns 
plt.figure(figsize=(12,8))
sns.scatterplot(x=y_test,y=y_final_pred,alpha=0.5,color='g')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title('Actual vs Predicted')
plt.show()

C:\Users\User\AppData\Local\Temp\ipykernel_72588\3591077729.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [23]:
df.head()

,gender,age,address,famsize,Pstatus,M_Edu,F_Edu,M_Job,F_Job,relationship,smoker,tuition_fee,time_friends,ssc_result,hsc_result
0,M,18,Rural,GT3,Together,3,2,At_home,Farmer,No,No,71672,4,4.22,3.72
1,F,19,Rural,LE3,Apart,0,4,Other,Health,Yes,No,26085,5,3.47,2.62
2,F,19,Rural,GT3,Together,0,3,Teacher,Services,No,No,40891,3,3.32,2.56
3,F,19,Rural,LE3,Apart,2,3,At_home,Business,No,No,50600,2,4.57,4.17
4,M,17,Rural,GT3,Together,1,1,At_home,Farmer,No,No,62458,2,4.50,3.94

In [24]:
from sklearn.model_selection import cross_val_score
rf_pipeline=Pipeline(
    [
        ('preprocessor',ColumnTransformer(
            transformers=[
                ('num',num_transformer,X.select_dtypes(include=np.number).columns),
                ('cat',cat_transformer,X.select_dtypes(exclude=np.number).columns)
            ]
        )),
        ('model',RandomForestRegressor(n_estimators=100,random_state=42))
    ]
)

In [25]:


cv_scores=cross_val_score(rf_pipeline,X_train,y_train,cv=10,scoring='neg_mean_squared_error')
cv_rmse=np.sqrt(-cv_scores)
print(cv_rmse)

[0.1422733  0.13062705 0.13229842 0.14680644 0.14795956 0.14658055
 0.15397954 0.13899758 0.12200084 0.13500019]

In [26]:
print(cv_rmse.std())

0.00921689795310348

In [27]:
##randomized searchcv 
from scipy.stats import randint 
my_dist=randint(1,11)
print(my_dist.rvs(size=6))

[7 2 3 3 3 4]

In [28]:
param_dist={
    'model__n_estimators':randint(100,500),
    'model__max_depth':[None,10,20],
    'model__min_samples_split':randint(1,10)

}

from sklearn.model_selection import RandomizedSearchCV
random_search=RandomizedSearchCV(
    estimator=rf_pipeline,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    n_jobs=-1,
    scoring='neg_mean_squared_error',
    verbose=2,
    random_state=42





)
random_search.fit(X_train,y_train)
print("Best Hyperparameters:",random_search.best_params_)

Fitting 5 folds for each of 50 candidates, totalling 250 fits

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
20 fits failed out of a total of 250.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\pipeline.py", line 663, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of RandomForestRegressor must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [-0.01989346 -0.01998468 -0.02009514 -0.01994948 -0.01993564 -0.01994183
 -0.01999624 -0.01999322 -0.01992381         nan -0.01989993 -0.01990527
 -0.01993674 -0.01990516 -0.01991116 -0.01994465 -0.01990482 -0.01996506
 -0.01994747 -0.02016255 -0.02014906 -0.01989821 -0.01995709 -0.01988862
 -0.0199788  -0.01998445 -0.01991868 -0.01997518 -0.02004586         nan
 -0.01998048 -0.02015519 -0.02015837 -0.01993302 -0.01993835 -0.0201974
 -0.01999271         nan -0.02015805 -0.01999149 -0.01989243 -0.01992126
 -0.01996663 -0.01996913 -0.02017569         nan -0.01991234 -0.01998063
 -0.0201833  -0.02018122]
  warnings.warn(

Best Hyperparameters: {'model__max_depth': 10, 'model__min_samples_split': 4, 'model__n_estimators': 369}

In [29]:
import pickle 
from sklearn.linear_model import LinearRegression
X_train_lr=[[1],[2],[3],[4],[5]]
y_train_lr=[10,20,30,40,50]
model=LinearRegression()
model.fit(X_train,y_train)
model.predict([[10]])[0]

ValueError: could not convert string to float: 'M'

In [ ]:
filename="lr.pkl"
with open(filename,"wb")as file :
    pickle.dump(model,file)

In [ ]:
with open("lr.pkl","rb") as file:
    loaded_model=pickle.load(file)

In [ ]:
loaded_model.predict([[7]])

array([70.])

In [ ]:
##saving random forest 
filename="random_forest_model.pkl"
with open(filename,"wb")as file:
    pickle.dump(random_search,file)

In [ ]:
with open("random_forest_model.pkl","rb")as file:
    loaded_rf_model=pickle.load(file)
    print(loaded_rf_model.predict(X_test))

[3.24813808 3.63936138 3.69632315 3.93415944 4.1076736  3.27072695
 4.09958465 2.50256598 2.10633699 3.2701777  3.57431522 2.92584264
 3.19929278 4.51298167 3.01386118 2.63695208 3.61628147 3.36786373
 2.87122621 2.88735632 2.74107849 3.18588724 2.89945616 3.22534203
 2.05461314 2.64539077 3.21802007 4.03430123 3.1203105  4.08801523
 2.45744916 3.83485003 4.50888024 2.56348902 3.20317019 3.21390665
 2.74812963 3.57604872 2.45020837 2.60565241 2.98895371 2.97619076
 3.66365835 2.76651367 2.32610757 3.01739181 2.61563775 2.70441272
 4.1070183  3.22731134 3.00102886 3.40829784 4.236945   3.53883388
 2.99426729 3.23744524 3.25401752 2.78525418 3.71359346 2.7038779
 3.03148646 2.65733352 2.5149602  4.43089257 2.58082166 3.21989986
 3.86168574 2.73406531 3.04757297 3.23642417 3.01372702 2.62950665
 2.70293356 3.43821656 3.04831729 2.78659414 3.54885181 3.00970432
 2.51008511 4.22198992 3.32861618 2.61590302 3.22596768 3.09251686
 2.37853671 3.37573203 3.69604185 2.71164173 2.82403445 4.16743503
 4.05746544 3.03742573 2.76271017 2.88179545 3.21690817 2.71190086
 2.89811804 2.47273518 2.75860799 3.18272918 3.22560647 3.06048102
 2.85378749 2.20379044 2.40870115 3.40018498 4.08815666 4.20259303
 3.29266431 2.08098855 2.99358176 4.03523283 3.43573751 2.9951894
 2.55378835 2.19645814 4.61117439 2.86500533 2.70030947 4.03242298
 3.51617525 3.46942012 3.1243289  2.62833779 4.38182059 3.54086855
 2.37428798 2.79167736 4.04415663 3.53280556 2.05046732 2.76225233
 2.78885714 2.51514957 2.77568167 2.81286825 2.64836236 4.04769331
 4.10132168 2.92598314 4.37214838 2.97321161 4.13996948 2.79206238
 2.84953974 4.53583892 2.66354486 3.33606078 3.28335282 2.24304126
 2.12526571 3.56144361 3.25935649 3.43723448 3.12668447 3.4627991
 4.49008742 4.26146433 3.07570846 4.3583075  3.60366676 3.15817556
 4.01526955 2.16027861 2.80824906 3.22283494 3.30722531 3.07920897
 2.34704662 2.54113262 2.61336115 3.1367989  2.60901298 2.87271137
 3.31411699 2.70327056 3.30589298 2.07159634 3.67624099 3.15408336
 3.84942975 2.35591918 3.60325118 3.78675304 2.29737451 3.57807771
 3.07616417 4.38612963 3.06702469 2.85221124 2.45121152 3.76408337
 3.63855707 3.11306397 2.66013053 3.00220161 2.29232879 3.03590366
 3.25080423 2.2145943  3.26957912 3.18277934 2.30399898 4.52544794
 2.95934372 2.63021103 3.41709216 3.44035449 4.26320039 2.87073783
 2.68515616 2.19585702 2.3910566  3.63548678 3.40044108 2.97588322
 4.09560443 2.32328395 2.58500842 4.34231675 3.3786412  2.06242222
 4.09452139 2.4938378  2.31614813 3.34266963 3.12974567 3.28271885
 2.78032276 3.93029541 3.33284513 2.62193826 3.06221837 2.3988756
 2.70891998 3.28387572 2.85920181 3.84514733 2.564748   3.52988634
 3.58338944 2.14272307 3.36571518 3.39814185 4.16998128 4.21797934
 3.26489112 3.02035378 2.42736184 2.43193121 3.38685787 3.16545928
 3.31928778 4.12584739 4.3771781  3.43037731 2.90307865 3.29047464
 2.88876708 3.77475371 3.00034549 2.46070012 3.32739323 3.03800093
 2.03964868 3.17654679 3.42680706 2.78332694 3.49649721 3.23998403
 3.14203876 3.3294072  2.94036417 3.00153526 2.60346091 3.25304543
 2.48368202 4.10676437 3.58433637 2.90351041 2.06607666 4.56861314
 2.69629922 2.71479321 2.79237779 3.56500733 2.95496429 2.25906708
 2.7189717  3.49240834 3.72768517 3.46002932 2.81932159 3.43378035
 4.1576358  2.70735489 3.20819186 3.66652468 4.06767828 4.51691309
 3.72735054 2.4120864  2.69390941 3.65786023 3.31931583 2.77797741
 3.942507   3.62174229 3.98236181 3.01366739 3.5402084  2.89906491
 3.62326205 3.03590956 2.61643338 3.21037124 2.25884807 2.84196585
 3.23044809 3.14432825 3.16642527 3.72186691 3.34180762 3.23306181
 3.91878864 3.0843259  3.21106837 3.39158486 3.14056638 2.82447453
 4.51342969 3.24126348 2.8041818  2.84445464 3.72667309 4.4562661
 2.54426562 3.11486582 3.56278108 3.29677342 4.10637136 2.7382687
 3.51429865 3.5088919  3.70912915 2.59689756 2.73605121 2.93014169
 3.01589454 4.06126    2.40729969 2.48034635 2.13349024 3.33079823
 3.48401489 4.35075094 3.0788902  3.35328473 2.7666442  3.55814436
 3.70500224 3.39930851 2.52341264 2.70102007 3.45178328 3.24457484
 3.24776325 4.18132767 2.77857487 4.12525605 2.84467712 3.08758785
 2.64988574 3.2046335  3.24563236 3.74350483 3.35402162 3.1002729
 2.14213277 3.54233525 4.25122593 3.69447732 3.45882064 3.14158221
 3.94856656 3.25984167 3.64692507 3.02739323 4.21973133 3.17986173
 3.58806875 3.28618599 2.85878967 2.98857268 2.6985     3.46477868
 3.26863041 2.58305423 3.36973083 2.92564582 2.36089395 3.27619591
 3.40764796 2.34047198]

In [ ]:
! pip install mlflow

Requirement already satisfied: mlflow in d:\anaconda3\lib\site-packages (3.9.0)
Requirement already satisfied: mlflow-skinny==3.9.0 in d:\anaconda3\lib\site-packages (from mlflow) (3.9.0)
Requirement already satisfied: mlflow-tracing==3.9.0 in d:\anaconda3\lib\site-packages (from mlflow) (3.9.0)
Requirement already satisfied: Flask-CORS<7 in d:\anaconda3\lib\site-packages (from mlflow) (6.0.2)
Requirement already satisfied: Flask<4 in d:\anaconda3\lib\site-packages (from mlflow) (2.3.3)
Requirement already satisfied: alembic!=1.10.0,<2 in d:\anaconda3\lib\site-packages (from mlflow) (1.18.3)
Requirement already satisfied: cryptography<47,>=43.0.0 in d:\anaconda3\lib\site-packages (from mlflow) (44.0.1)
Requirement already satisfied: docker<8,>=4.0.0 in d:\anaconda3\lib\site-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in d:\anaconda3\lib\site-packages (from mlflow) (3.4.3)
Requirement already satisfied: huey<3,>=2.5.4 in d:\anaconda3\lib\site-packages (from mlflow) (2.6.0)
Requirement already satisfied: matplotlib<4 in d:\anaconda3\lib\site-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in d:\anaconda3\lib\site-packages (from mlflow) (2.1.3)
Requirement already satisfied: pandas<3 in d:\anaconda3\lib\site-packages (from mlflow) (2.2.3)
Requirement already satisfied: pyarrow<23,>=4.0.0 in d:\anaconda3\lib\site-packages (from mlflow) (19.0.0)
Requirement already satisfied: scikit-learn<2 in d:\anaconda3\lib\site-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in d:\anaconda3\lib\site-packages (from mlflow) (1.15.3)
Requirement already satisfied: skops<1 in d:\anaconda3\lib\site-packages (from mlflow) (0.13.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in d:\anaconda3\lib\site-packages (from mlflow) (2.0.39)
Requirement already satisfied: waitress<4 in d:\anaconda3\lib\site-packages (from mlflow) (3.0.2)
Requirement already satisfied: cachetools<7,>=5.0.0 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (8.1.8)
Requirement already satisfied: cloudpickle<4 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (3.0.0)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (0.85.0)
Requirement already satisfied: fastapi<1 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (0.128.0)
Requirement already satisfied: gitpython<4,>=3.1.9 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (3.1.43)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (8.5.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (1.39.1)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (1.39.1)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (1.39.1)
Requirement already satisfied: packaging<26 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (24.2)
Requirement already satisfied: protobuf<7,>=3.12.0 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (6.33.5)
Requirement already satisfied: pydantic<3,>=2.0.0 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (2.10.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (1.0.0)
Requirement already satisfied: pyyaml<7,>=5.1 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (2.32.3)
Requirement already satisfied: sqlparse<1,>=0.4.0 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in d:\anaconda3\lib\site-packages (from mlflow-skinny==3.9.0->mlflow) (0.40.0)
Requirement already satisfied: Mako in d:\anaconda3\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: colorama in d:\anaconda3\lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.9.0->mlflow) (0.4.6)
Requirement already satisfied: cffi>=1.12 in d:\anaconda3\lib\site-packages (from cryptography<47,>=43.0.0->mlflow) (1.17.1)
Requirement already satisfied: google-auth~=2.0 in d:\anaconda3\lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.9.0->mlflow) (2.48.0)
Requirement already satisfied: pywin32>=304 in d:\anaconda3\lib\site-packages (from docker<8,>=4.0.0->mlflow) (308)
Requirement already satisfied: urllib3>=1.26.0 in d:\anaconda3\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.3.0)
Requirement already satisfied: starlette<0.51.0,>=0.40.0 in d:\anaconda3\lib\site-packages (from fastapi<1->mlflow-skinny==3.9.0->mlflow) (0.50.0)
Requirement already satisfied: annotated-doc>=0.0.2 in d:\anaconda3\lib\site-packages (from fastapi<1->mlflow-skinny==3.9.0->mlflow) (0.0.4)
Requirement already satisfied: Werkzeug>=2.3.7 in d:\anaconda3\lib\site-packages (from Flask<4->mlflow) (2.3.7)
Requirement already satisfied: Jinja2>=3.1.2 in d:\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in d:\anaconda3\lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: blinker>=1.6.2 in d:\anaconda3\lib\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in d:\anaconda3\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.9.0->mlflow) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in d:\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.9.0->mlflow) (4.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in d:\anaconda3\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.9.0->mlflow) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in d:\anaconda3\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.9.0->mlflow) (4.9.1)
Requirement already satisfied: graphql-core<3.3,>=3.1 in d:\anaconda3\lib\site-packages (from graphene<4->mlflow) (3.2.7)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in d:\anaconda3\lib\site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in d:\anaconda3\lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in d:\anaconda3\lib\site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.9.0->mlflow) (3.21.0)
Requirement already satisfied: contourpy>=1.0.1 in d:\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (1.3.1)
Requirement already satisfied: cycler>=0.10 in d:\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (1.4.8)
Requirement already satisfied: pillow>=8 in d:\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (3.2.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.60b1 in d:\anaconda3\lib\site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.9.0->mlflow) (0.60b1)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda3\lib\site-packages (from pandas<3->mlflow) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda3\lib\site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in d:\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.9.0->mlflow) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in d:\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.9.0->mlflow) (2.27.1)
Requirement already satisfied: six>=1.5 in d:\anaconda3\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.9.0->mlflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.9.0->mlflow) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.9.0->mlflow) (2025.4.26)
Requirement already satisfied: pyasn1>=0.1.3 in d:\anaconda3\lib\site-packages (from rsa<5,>=3.1.4->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.9.0->mlflow) (0.4.8)
Requirement already satisfied: joblib>=1.2.0 in d:\anaconda3\lib\site-packages (from scikit-learn<2->mlflow) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\anaconda3\lib\site-packages (from scikit-learn<2->mlflow) (3.5.0)
Requirement already satisfied: prettytable>=3.9 in d:\anaconda3\lib\site-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet!=0.4.17 in d:\anaconda3\lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.1.1)
Requirement already satisfied: anyio<5,>=3.6.2 in d:\anaconda3\lib\site-packages (from starlette<0.51.0,>=0.40.0->fastapi<1->mlflow-skinny==3.9.0->mlflow) (4.7.0)
Requirement already satisfied: sniffio>=1.1 in d:\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette<0.51.0,>=0.40.0->fastapi<1->mlflow-skinny==3.9.0->mlflow) (1.3.0)
Requirement already satisfied: h11>=0.8 in d:\anaconda3\lib\site-packages (from uvicorn<1->mlflow-skinny==3.9.0->mlflow) (0.16.0)
Requirement already satisfied: pycparser in d:\anaconda3\lib\site-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in d:\anaconda3\lib\site-packages (from Jinja2>=3.1.2->Flask<4->mlflow) (3.0.2)
Requirement already satisfied: wcwidth in d:\anaconda3\lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.2.5)

In [ ]:
import mlflow 

mlflow.set_tracking_uri("mlruns")
mlflow.set_experiment("test_run")
with mlflow.start_run(run_name='dummy_test'):
    mlflow.log_metric("Accuracy",0.95)
    mlflow.log_metric("loss",0.05)
    mlflow.log_param("model","fake_modelv1")
    mlflow.log_param("Learning Rate",0.01)

2026/02/08 01:11:13 INFO mlflow.tracking.fluent: Experiment with name 'test_run' does not exist. Creating a new experiment.

In [31]:
##RFMLFLOW
import mlflow 
import mlflow.sklearn 
import numpy as np 
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error 
from sklearn.ensemble import RandomForestRegressor  
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
mlflow.set_experiment("RFBSP")
my_params={
    'n_estimators':100,
    'max_depth':10,
    'random_state':42
}
simple_rf_pipeline=Pipeline(
    [
        ('preprocessor',ColumnTransformer(
            transformers=[
                ('num',num_transformer,X.select_dtypes(include=np.number).columns),
                ('cat',cat_transformer,X.select_dtypes(exclude=np.number).columns)
            ]
        )),
        ('model',RandomForestRegressor(**my_params))
    ]
)
with mlflow.start_run(run_name='singlerf'):
 mlflow.log_params(my_params)
 mlflow.log_param("model","RandomForestRegressor")
 simple_rf_pipeline.fit(X_train,y_train)
 y_train_pred=simple_rf_pipeline.predict(X_train)
 train_rmse=np.sqrt(mean_squared_error(y_train,y_train_pred))
 mlflow.log_metric("train_rmse",train_rmse)
 y_test_pred=simple_rf_pipeline.predict(X_test)
 test_rmse=np.sqrt(mean_squared_error(y_test,y_test_pred))
 mlflow.log_metric("test_rmse",test_rmse)

2026/02/08 01:35:12 INFO mlflow.tracking.fluent: Experiment with name 'RFBSP' does not exist. Creating a new experiment.